### ISSUE TITLE
When responding to an email, the to-address-field is focussed

### ISSUE THREAD

**Issue by cyberbeat** [Welpy-cw/Folder-Account#8] opened 2021-10-18 20:23 UTC
When I try to respond to an email, the response window is opened with the to-address field focussed, which makes no sense, since the address field is already filled with the reponse-address.

This only happens, when this addon is activated. And only if the checkbox in folder-properties "ignore on reply" is not checked (this is the default)

**Comment by jobisoft** [comment] 2021-10-19 08:18
Is this add-on using a WebExtension API to open the reply window? is this a dupe of 
https://bugzilla.mozilla.org/show_bug.cgi?id=1732558?

**Comment by Welpy-cw** [comment] 2021-10-19 13:42
@jobisoft 

> Is this add-on using a WebExtension API to open the reply window?

It just uses getComposeDetails/setComposeDetails after NotifyComposeFieldsReady has fired.

> is this a dupe of https://bugzilla.mozilla.org/show_bug.cgi?id=1732558?

If I'm not mistaken compose.beginReply calls openComposeWindow, which in turn calls compose.setComposeDetails ...

**Comment by Welpy-cw** [comment] 2021-10-21 15:45
@cyberbeat 

I just published a [new pre-release version](https://github.com/Welpy-cw/Folder-Account/releases) containing a workaround. Please test!

**Comment by cyberbeat** [comment] 2021-10-21 17:40
Great, thanks! It works.

**Comment by Welpy-cw** [comment] 2021-11-07 10:55
Causing this behavior is a [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1732558) in Thunderbird that already has been fixed in the development version and hopefully will be backported to the next release (91.4). Reopened the issue for the time being.

**Comment by Welpy-cw** [comment] 2021-11-17 21:04
The mentioned bug has been fixed in Thunderbird 91.3.1 as well as 95.0b2, therefore pre-release 11.1.1 of this add-on isn't needed anymore and has been removed. Closing issue.

**Closed as completed by Welpy-cw** 2021-11-17 21:04 UTC
Labels: thunderbird issue
